App\Entity\Customer:
  collectionOperations:
    get:
      normalization_context:
        groups: [ 'customer:item:get' ]
    list:
      normalization_context:
        groups: ['customer:collection:get']
    post:
      normalization_context:
        groups: [ 'customer:item:get' ]
      denormalization_context:
        groups: [ 'customer:collection:post' ]
    itemOperations:
      post:
        normalization_context:
          groups: [ 'customer:item:get' 'user:item:get' ]
        denormalization_context:
          groups: [ 'user:item:post' ]
      delete:
        normalization_context:
          groups: ['customer:item:get' 'user:item:get']
      denormalization_context:
          groups: ['user:item:delete']

