App\Entity\Product:
  collectionOperations:
    get:
      normalization_context:
        groups: [ 'product:collection:get']
  itemOperations:
    get:
      normalization_context:
        groups: [ 'product:item:get' ]

