App\Entity\Customer:
  attributes:
    id:
      groups: ['customer:item:get']
    company:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post']
    lastname:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    firstname:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    address:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    city:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    phoneNumber:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    country:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    postalCode:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    email:
      groups: [ 'customer:item:get', 'customer:collection:get', 'customer:item:post' ]
    users:
      groups: [ 'customer:item:get', 'customer:collection:get']




